// Add independently verified models here. Keep per-GPU units and workload provenance explicit.
const defaults = {
  hardware: 'B300',
  workload: 'AgentX agentic coding',
  interactivity: 50,
  defaultGpuCount: 8,
  defaultHourlyRate: 5.5,
  defaultHoursPerMonth: 730,
  methodology: 'https://inferencex.semianalysis.com/agentx',
  pricesAsOf: '2026-09-30',
};

const glm52 = {
  ...defaults,
  id: 'glm-52-b300',
  name: 'GLM-5.2',
  engine: 'SGLang · FP4',
  measuredAt: '2026-09-11',
  inputTpsPerGpu: 18297.02036,
  outputTpsPerGpu: 117.82428,
  cacheHitRate: 0.9118570192606615,
  measuredGpuCount: 8,
  benchmarkModel: 'glm5.2',
  benchmarkIds: ['441520'],
  capacityKind: 'measured',
  source: 'https://github.com/SemiAnalysisAI/InferenceX/actions/runs/34528653758/attempts/1',
  sourceApi: 'https://inferencex.semianalysis.com/api/v1/views/calculator?model=GLM-5.2&sequence=agentic-traces&gpus=b300_sglang&target=50&percentile=p90&precisions=fp4&runId=34528653758',
  assumptions: 'Measured on one 8-GPU server, with cache offloading enabled. The fastest published point meeting the 50 tok/s/user target is 24 concurrent sessions at 85.8 tok/s/user (p90), with a 2.25-second p90 wait for the first token. Cache share follows the AgentX calculator, including external cache hits. The cheaper price reference is Baidu’s current promotional quote on OpenRouter, not a guaranteed six-month rate.',
  prices: [
    { id: 'zai', name: 'Z.AI', input: 1.4, cached: 0.26, output: 4.4, source: 'https://docs.z.ai/guides/overview/pricing' },
    { id: 'baidu', name: 'OpenRouter · Baidu', input: 0.29925, cached: 0.07448, output: 1.04804, source: 'https://openrouter.ai/z-ai/glm-5.2/providers' },
  ],
};

export const models = [{
  id: 'deepseek-v41-flash-b300',
  name: 'DeepSeek V4.1 Flash', hardware: 'B300', engine: 'vLLM · FP4',
  measuredAt: '2026-09-29', workload: 'AgentX agentic coding',
  inputTpsPerGpu: 215846.58858871702, outputTpsPerGpu: 1832.0224774118158,
  cacheHitRate: 0.9412923639315768, interactivity: 50,
  defaultGpuCount: 8, defaultHourlyRate: 5.5, defaultHoursPerMonth: 730,
  source: 'https://inferencex.semianalysis.com/run/deepseek-v41-flash-on-b300',
  methodology: 'https://inferencex.semianalysis.com/agentx',
  sourceApi: 'https://inferencex.semianalysis.com/api/v1/views/calculator?model=DeepSeek-V4.1-Flash&sequence=agentic-traces&gpus=b300_vllm&target=50',
  assumptions: 'Eight-GPU capacity assumes linear replication of the published per-GPU result. Throughput is total input plus output, not generation speed. This is a fixed benchmark workload, not measured OpenRouter demand.',
  prices: [
    { id: 'deepseek', name: 'DeepSeek off-peak', input: 0.15, cached: 0.003, output: 0.60 },
    { id: 'openinference', name: 'OpenInference reference', input: 0.0198, cached: 0.00291, output: 0.396 },
  ],
  pricesAsOf: '2026-09-30',
}, {
  ...defaults,
  id: 'deepseek-v4-pro-b300',
  name: 'DeepSeek V4 Pro',
  engine: 'vLLM · FP4',
  measuredAt: '2026-09-28',
  inputTpsPerGpu: 71409.71574378308,
  outputTpsPerGpu: 545.6144661939521,
  cacheHitRate: 0.9369621004097932,
  measuredGpuCount: 8,
  benchmarkModel: 'dsv4',
  benchmarkIds: ['443288', '443283'],
  capacityKind: 'interpolated',
  source: 'https://github.com/SemiAnalysisAI/InferenceX/actions/runs/36377107106/attempts/1',
  sourceApi: 'https://inferencex.semianalysis.com/api/v1/views/calculator?model=DeepSeek-V4-Pro&sequence=agentic-traces&gpus=b300_vllm&target=50&percentile=p90&precisions=fp4&runId=36377107106',
  assumptions: 'AgentX interpolates between measured 128- and 192-session runs on one 8-GPU server, using FP4, speculative decoding and cache offloading. Those runs had 16.8–21.8-second p90 waits for the first token; the 50 tok/s/user target does not impose a first-token latency limit. Prices are V4 Pro 0813 rates. StreamLake’s current OpenRouter quote matches DeepSeek off-peak for this mix. Peak and off-peak lines are separate constant-price scenarios, not a time-weighted forecast.',
  prices: [
    { id: 'deepseek-offpeak', name: 'DeepSeek off-peak', input: 0.66, cached: 0.022, output: 1.98, source: 'https://api-docs.deepseek.com/quick_start/pricing/' },
    { id: 'deepseek-peak', name: 'DeepSeek peak', input: 1.32, cached: 0.044, output: 3.96, source: 'https://openrouter.ai/deepseek/deepseek-v4-pro-0813/providers' },
  ],
}, glm52, {
  ...glm52,
  id: 'glm-53-proxy-b300',
  name: 'GLM-5.3 (estimate)',
  estimateFrom: 'GLM-5.2',
  capacityKind: 'proxy',
  assumptions: 'Planning estimate, not a measured GLM-5.3 B300 result. Z.AI says 5.3 uses the same base model as 5.2, with changes from post-training. This estimate reuses 5.2 throughput, cache share, FP4 precision and 8-GPU configuration, but uses current 5.3 prices. Real task lengths, speculative acceptance and runtime optimizations may differ. The 5.2 source point runs at 85.8 tok/s/user (p90), with a 2.25-second p90 first-token wait. Validate on 5.3 before reserving hardware.',
  extraSources: [['Why a 5.2 proxy is reasonable', 'https://github.com/zai-org/GLM-5#glm-53--glm-53-flash']],
  prices: [
    { id: 'zai', name: 'Z.AI', input: 1.4, cached: 0.26, output: 4.4, source: 'https://docs.z.ai/guides/overview/pricing' },
    { id: 'atlas', name: 'OpenRouter · AtlasCloud', input: 0.602, cached: 0.1118, output: 1.892, source: 'https://openrouter.ai/z-ai/glm-5.3/providers' },
  ],
}, {
  ...defaults,
  id: 'kimi-k3-b300',
  name: 'Kimi K3',
  engine: 'vLLM · FP4',
  measuredAt: '2026-08-16',
  inputTpsPerGpu: 6035.460160799166,
  outputTpsPerGpu: 47.51736799076039,
  cacheHitRate: 0.8828103996289339,
  measuredGpuCount: 8,
  benchmarkModel: 'kimik3',
  benchmarkIds: ['439935', '439941'],
  capacityKind: 'interpolated',
  source: 'https://github.com/SemiAnalysisAI/InferenceX/actions/runs/31893747354/attempts/2',
  sourceApi: 'https://inferencex.semianalysis.com/api/v1/views/calculator?model=Kimi-K3&sequence=agentic-traces&gpus=b300_vllm&target=50&percentile=p90&precisions=fp4&runId=31893747354',
  assumptions: 'AgentX interpolates between measured 8- and 16-session runs on one 8-GPU server, using FP4, speculative decoding and cache offloading. Those runs had 2.28–3.23-second p90 waits for the first token. Cache share follows the AgentX calculator, including external cache hits. Price references use OpenRouter’s published input, cache-read and output rates for Moonshot and Relace; no extra cache-write revenue is assumed. These August results may lag newer serving optimizations.',
  prices: [
    { id: 'moonshot', name: 'Moonshot', input: 3, cached: 0.3, output: 15, source: 'https://openrouter.ai/moonshotai/kimi-k3/providers' },
    { id: 'relace', name: 'OpenRouter · Relace', input: 0.28, cached: 0.28, output: 10, source: 'https://openrouter.ai/moonshotai/kimi-k3/providers' },
  ],
}];
